[package]
name = "rust_game"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
bevy_prototype_lyon = "0.3.0"
rustc-hash = "1.1.0"
petgraph = "0.6"
benimator = "0.3.1"
